# Generated by Django 3.2.23 on 2024-02-19 05:55

from django.db import migrations, models
from django.utils import timezone

def create_initial_records(apps, schema_editor):
   Activity = apps.get_model('MindCareApp', 'Activity')  # Replace YourModel with the actual model name

   initial_records = [
        {'emotion': 'sad', 'type': 'meditation', 'activity_name': 'Meditation', 'image': 'activity/pexels-prasanth-inturi-1051838.jpg', 'is_enabled': 1, 'timestamp': timezone.now()},
        {'emotion': 'angry', 'type': 'breathing', 'activity_name': 'Breathing Exercise', 'image': 'activity/pexels-ivan-samkov-6648547.jpg', 'is_enabled': 1, 'timestamp': timezone.now()},
        {'emotion': 'neutral', 'type': 'walking', 'activity_name': 'Walking', 'image': 'activity/pexels-agung-pandit-wiguna-1149923.jpg', 'is_enabled': 1, 'timestamp': timezone.now()},
        {'emotion': 'happy', 'type': 'music', 'activity_name': 'Music', 'image': 'activity/pexels-suvan-chowdhury-144429.jpg', 'is_enabled': 1, 'timestamp': timezone.now()},
        {'emotion': 'sad', 'type': 'comedy', 'activity_name': 'Comedy clips', 'image': 'activity/pexels-gratisography-476.jpg', 'is_enabled': 1, 'timestamp': timezone.now()},
    ]
   for record_data in initial_records:
        Activity.objects.create(**record_data)

class Migration(migrations.Migration):

    dependencies = [
        ('MindCareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=50)),
                ('activity_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(default=None, upload_to='activity/')),
                ('is_enabled', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.RunPython(create_initial_records),

    ]
