# Generated by Django 3.2.23 on 2024-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindCareApp', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(error_messages={'unique': 'This contact number is already exist.'}, max_length=50, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'This email address is already exist.'}, max_length=100, unique=True)),
                ('image', models.ImageField(default=None, upload_to='professionals/')),
                ('location', models.TextField(default=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_enabled', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'professionals',
            },
        ),
    ]
