# Generated by Django 3.2.23 on 2024-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindCareApp', '0003_professionals'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionals',
            name='specialty',
            field=models.CharField(default='', max_length=100),
        ),
    ]
