# Generated by Django 3.2.23 on 2024-02-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindCareApp', '0004_professionals_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=20)),
                ('sender', models.CharField(max_length=20)),
                ('emotion', models.CharField(default='', max_length=20)),
                ('content', models.TextField(db_collation='utf8mb4_general_ci')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MindCareApp.user')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
