# Generated by Django 3.2.23 on 2024-02-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindCareApp', '0005_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='emotion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
